### ISSUE TITLE
ipdl_parser fails to build on OSX 10.10.5 due to stack overflow

### ISSUE THREAD

**Issue by mikeconley** [amccreight/ipdl_parser#29]
When I attempt to build latest tip (65bf74f62050d962687d6adedbe84e079e7d0246), I get

```
error: failed to run custom build command for `lalrpop v0.13.1`
process didn't exit successfully: `/Users/mikeconley/Projects/ipdl_parser/target/debug/build/lalrpop-44ca18171886e540/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
processing file `/Users/mikeconley/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.13.1/src/parser/lrgrammar.lalrpop`

--- stderr

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

I'll start bisecting.

**Comment by mikeconley** [comment]
Unfortunately, I can't effectively bisect because early commits also don't build for different reasons - I get compilation errors like:

```
error[E0034]: multiple applicable items in scope
   --> /Users/mikeconley/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.1.18/src/graph.rs:404:17
    |
404 |         assert!(Ix::max().index() == !0 || NodeIndex::end() != node_idx);
    |                 ^^^^^^^ multiple `max` found
    |
note: candidate #1 is defined in the trait `graph::IndexType`
```

So I'm not sure what's up here. :/

**Comment by mikeconley** [comment]
Also, to be clear, I'm using rustc 1.21.0 (3b72af97e 2017-10-09)

**Comment by mikeconley** [comment]
I'm on macOS 10.10.5 (Yosemite)

And yeah, just using straight-up `cargo build`.

**Comment by amccreight** [comment]
I'm on OSX 10.12.6 (Sierra). Maybe you need to upgrade your OS? Somehow? :P Or try a clobber build?

**Comment by mikeconley** [comment]
Clobber build was a no-go.

I guess I can just develop on my Ubuntu VM for now until I get around to upgrading to the latest-and-greatest from Apple. :D

**Comment by amccreight** [comment]
We should keep this in mind if we want to actually land this in mozilla-central. I do recall some problem with stack overflows that they had with Stylo on earlier versions of OSX, so this could be related. I think they were limiting the stack size, so not the same thing exactly.

**Comment by amccreight** [comment]
Maybe you could file a bug with lalrpop about this issue?
